apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrid-image-editor.name" . }}
  labels:
    {{- include "hybrid-image-editor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hybrid-image-editor.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
